---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: jailbreak-detect-cache
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/nvidia/nemoguard-jailbreak-detect:1.0.0
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model: {}
  storage:
    pvc:
      create: true
      storageClass: ""
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
  resources: {}
