
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: deepseek-r1
spec:
  env:
  - name: NIM_USE_SGLANG
    value: "1"
  - name: NIM_MULTI_NODE
    value: "1"
  - name: NIM_TENSOR_PARALLEL_SIZE
    value: '8'
  - name: NIM_PIPELINE_PARALLEL_SIZE
    value: '2'
  - name: NGC_HOME
    value: /model-store/ngc/hub
  - name: HF_HOME
    value: /model-store/huggingface/hub
  - name: NUMBA_CACHE_DIR
    value: /tmp/numba
  - name: OUTLINES_CACHE_DIR
    value: /tmp/outlines
  - name: UCX_TLS
    value: ib,tcp,shm
  - name: UCC_TLS
    value: ucp
  - name: UCC_CONFIG_FILE
    value: " "
  - name: GLOO_SOCKET_IFNAME
    value: eth0
  - name: NCCL_SOCKET_IFNAME
    value: eth0
  - name: NIM_TRUST_CUSTOM_CODE
    value: "1"
  - name: NIM_NODE_RANK
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
  readinessProbe:
    probe:
      failureThreshold: 3
      httpGet:
        path: "/v1/health/ready"
        port: "api"
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  startupProbe:
    probe:
      failureThreshold: 100
      httpGet:
        path: "/v1/health/ready"
        port: "api"
      initialDelaySeconds: 900
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  image:
    repository: nvcr.io/nim/deepseek-ai/deepseek-r1
    tag: "1.7.3"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: deepseek-r1-nimcache
      # profile: '12c2a31b069ad9d7c027fcec7083e3c1c900d75211de97f15df9beb45a81e954'
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 8
    requests:
      nvidia.com/gpu: 8
  expose:
    service:
      type: ClusterIP
      port: 8000
  multiNode:
    size: 2
    gpusPerPod: 8
    mpi:
      mpiStartTimeout: 6000
