/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/NVIDIA/k8s-nim-operator/api/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// NIMBuilds returns a NIMBuildInformer.
	NIMBuilds() NIMBuildInformer
	// NIMCaches returns a NIMCacheInformer.
	NIMCaches() NIMCacheInformer
	// NIMPipelines returns a NIMPipelineInformer.
	NIMPipelines() NIMPipelineInformer
	// NIMServices returns a NIMServiceInformer.
	NIMServices() NIMServiceInformer
	// NemoCustomizers returns a NemoCustomizerInformer.
	NemoCustomizers() NemoCustomizerInformer
	// NemoDatastores returns a NemoDatastoreInformer.
	NemoDatastores() NemoDatastoreInformer
	// NemoEntitystores returns a NemoEntitystoreInformer.
	NemoEntitystores() NemoEntitystoreInformer
	// NemoEvaluators returns a NemoEvaluatorInformer.
	NemoEvaluators() NemoEvaluatorInformer
	// NemoGuardrails returns a NemoGuardrailInformer.
	NemoGuardrails() NemoGuardrailInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// NIMBuilds returns a NIMBuildInformer.
func (v *version) NIMBuilds() NIMBuildInformer {
	return &nIMBuildInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NIMCaches returns a NIMCacheInformer.
func (v *version) NIMCaches() NIMCacheInformer {
	return &nIMCacheInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NIMPipelines returns a NIMPipelineInformer.
func (v *version) NIMPipelines() NIMPipelineInformer {
	return &nIMPipelineInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NIMServices returns a NIMServiceInformer.
func (v *version) NIMServices() NIMServiceInformer {
	return &nIMServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NemoCustomizers returns a NemoCustomizerInformer.
func (v *version) NemoCustomizers() NemoCustomizerInformer {
	return &nemoCustomizerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NemoDatastores returns a NemoDatastoreInformer.
func (v *version) NemoDatastores() NemoDatastoreInformer {
	return &nemoDatastoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NemoEntitystores returns a NemoEntitystoreInformer.
func (v *version) NemoEntitystores() NemoEntitystoreInformer {
	return &nemoEntitystoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NemoEvaluators returns a NemoEvaluatorInformer.
func (v *version) NemoEvaluators() NemoEvaluatorInformer {
	return &nemoEvaluatorInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NemoGuardrails returns a NemoGuardrailInformer.
func (v *version) NemoGuardrails() NemoGuardrailInformer {
	return &nemoGuardrailInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
