# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: main
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
    - dependencies
    groups:
      k8sio:
        patterns:
        - k8s.io/*
        exclude-patterns:
        - k8s.io/klog/*

  - package-ecosystem: "docker"
    directory: "/deployments/container"
    schedule:
      interval: "daily"

  # Github actions need to be updated on main
  - package-ecosystem: "github-actions"
    target-branch: main
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    target-branch: main
    directory: "deployments/devel"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    target-branch: main
    directory: "/deployments/devel"
    schedule:
      interval: "daily"
