apiVersion: apps.nvidia.com/v1alpha1
kind: NemoCustomizer
metadata:
  name: nemocustomizer-sample
  namespace: nemo
spec:
  wandbSecret:
    name: wandb-secret
    apiKeyKey: encryptionKey
  otel:
    enabled: true
    exporterOtlpEndpoint: http://customizer-otel-opentelemetry-collector.nemo.svc.cluster.local:4317
  databaseConfig:
    credentials:
      user: ncsuser
      secretName: customizer-pg-existing-secret
      passwordKey: password
    host: customizer-pg-postgresql.nemo.svc.cluster.local
    port: 5432
    databaseName: ncsdb
  expose:
    service:
      type: ClusterIP
      port: 8000
  image:
    repository: nvcr.io/nvidia/nemo-microservices/customizer-api
    tag: "25.04"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  entitStoreIrl: http://nemoentitystore-sample.nemo.svc.cluster.local:8000
  nemoDatastoreUrl: http://nemodatastore-sample.nemo.svc.cluster.local:8000
  mlflowTrackingUrl: http://mlflow-tracking.nemo.svc.cluster.local:80
  nemoDatastoreTools:
    image: nvcr.io/nvidia/nemo-microservices/nds-v2-huggingface-cli:25.04
    imagePullSecrets: ngc-secret
  modelDownloadJobs:
    image: "nvcr.io/nvidia/nemo-microservices/customizer-api:25.04"
    imagePullPolicy: "IfNotPresent"
    imagePullSecrets:
      - name: ngc-secret
    ngcAPISecret: ngc-api-secret
    ngcAPISecretKey: "NGC_API_KEY"
    securityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
    # -- Time to live in seconds after the job finishes.
    ttlSecondsAfterFinished: 600
    # -- Interval in seconds to poll for model download status.
    pollIntervalSeconds: 15
  trainingConfig:
    name: nemo-training-config
  modelConfig:
    name: nemo-model-config
