---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: content-safety-cache
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/nvidia/llama-3.1-nemoguard-8b-content-safety:1.0.0
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        engine: tensorrt_llm
        tensorParallelism: "1"
  storage:
    pvc:
      create: true
      storageClass: ""
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
  resources: {}
