apiVersion: v1
kind: Secret
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
  {{- if .Labels }}
    {{- .Labels | yaml | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Annotations }}
    {{- .Annotations | yaml | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .SecretMapData }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
