apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
  {{- if .Labels }}
    {{- .Labels | yaml | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Annotations }}
    {{- .Annotations | yaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Type }}
  selector:
  {{- if .SelectorLabels }}
    {{- .SelectorLabels | yaml | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Ports }}
      {{- range .Ports }}
    - port: {{ .Port }}
      targetPort: {{ .TargetPort }}
      protocol: {{ .Protocol }}
      name: {{ .Name }}
      {{- end }}
    {{- else }}
    - port: {{ .Port }}
      {{- if .TargetPort }}
      targetPort: {{ .TargetPort }}
      {{- end }}
      {{- if .Protocol }}
      protocol: {{ .Protocol }}
      {{- end }}
      {{- if .PortName }}
      name: {{ .PortName }}
      {{- end }}
    {{- end }}
