apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  {{- if .Labels }}
  labels:
    {{- .Labels | yaml | nindent 4 }}
  {{- end }}
  {{- if .Annotations }}
  annotations:
    {{- .Annotations | yaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Type | default "ClusterIP" }}
  {{- if .SelectorLabels }}
  selector:
    {{- .SelectorLabels | yaml | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Ports }}
      {{- range .Ports }}
    - port: {{ .Port }}
      targetPort: {{ .TargetPort }}
      protocol: {{ .Protocol | default "TCP" }}
      name: {{ .Name }}
      {{- end }}
    {{- else if .Port }}
    - port: {{ .Port }}
      {{- if .TargetPort }}
      targetPort: {{ .TargetPort }}
      {{- end }}
      protocol: {{ .Protocol | default "TCP" }}
      {{- if .Name }}
      name: {{ .Name }}
      {{- end }}
    {{- end }}

