{{- if .Enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
  {{- if .Labels }}
    {{- .Labels | yaml | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Annotations }}
    {{- .Annotations | yaml | nindent 4 }}
  {{- end }}
spec:
  {{- if .SMSpec }}
    {{- .SMSpec | yaml | nindent 2 }}
  {{- end }}
{{- end }}
