# permissions for end users to view nemoguardrails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: kustomize
  name: nemoguardrails-viewer-role
rules:
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemoguardrails
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemoguardrails/status
  verbs:
  - get
