# This rule is not used by the project k8s-nim-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.nvidia.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: kustomize
  name: nimbuild-admin-role
rules:
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimbuilds
  verbs:
  - '*'
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimbuilds/status
  verbs:
  - get
