# permissions for end users to edit nimpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: kustomize
  name: nimpipeline-editor-role
rules:
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimpipelines/status
  verbs:
  - get
