apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: meta-llama3-1b-instruct-datastore
spec:
  source:
    dataStore:
      endpoint: http://nemodatastore-sample.nemo.svc.cluster.local:8000/v1/hf
      modelName: "llama-3-1b-instruct"
      authSecret: hf-auth
      modelPuller: nvcr.io/nvidia/nemo-microservices/nds-v2-huggingface-cli:25.04
      pullSecret: nvcrimagepullsecret
  storage:
    pvc:
      create: true
      storageClass: ""
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
---

apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: meta-llama3-8b-instruct-ngc
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/meta/llama-3.1-8b-instruct:1.3.3
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        engine: tensorrt_llm
        tensorParallelism: "1"
  storage:
    pvc:
      create: true
      storageClass: ""
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
