apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: k8s-nim-operator
  name: nimcache-sample
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/meta/llama3-8b-instruct:1.0.3
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        profiles: []
        autoDetect: true
        precision: "fp8"
        engine: "tensorrt_llm"
        qosProfile: "throughput"
        gpus:
          product: "l40s"
          ids:
            - "26b5"
        tensorParallelism: "1"
  storage:
    pvc:
      create: true
      storageClass: "local-path"
      size: "50Gi"
      volumeAccessMode: ReadWriteOnce
