apiVersion: apps.nvidia.com/v1alpha1
kind: NemoEvaluator
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: kustomize
  name: nemoevaluator-sample
spec:
  image:
    repository: nvcr.io/nvidia/nemo-microservices/evaluation-ms
    tag: "25.01"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  argoWorkFlows:
    endpoint: "http://argo-workflows-server:2746"
    serviceAccount: "argo-workflows-executor"
  milvus:
    endpoint: "http://milvus-eval:19530"
  dataStore:
    endpoint: "http://datastore.default.svc.cluster.local:3000/v1/hf"
  databaseConfig:
    host: "evaluator-pg-postgresql"
    port: 5432
    databaseName: "evaluation"
    credentials:
      user: "nemo"
      secretName: "evaluator-pg-postgresql"
      passwordKey: "password"
  replicas: 1
