apiVersion: apps.nvidia.com/v1alpha1
kind: NemoGuardrails
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: k8s-nim-operator
  name: nemoguardrails-sample
  namespace: nemo
spec:
  authSecret: ngc-api-secret
  configStore:
    configMap:
      name: gr-config
  env:
    - name: NIM_ENDPOINT_URL
      value: "http://<NIM_SERVICE_ENDPOINT>:<NIM_SERVICE_PORT>/v1"
    - name: NIM_ENDPOINT_API_KEY
      value: dummy
  expose:
    ingress:
      spec: {}
    service:
      port: 7331
      type: ClusterIP
  image:
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
    repository: nvcr.io/nvidian/nemo-llm/guardrails
    tag: "25.03-rc16"
  metrics:
    serviceMonitor: {}
  replicas: 1
  resources:
    limits:
      cpu: "1"
      ephemeral-storage: 10Gi
