apiVersion: apps.nvidia.com/v1alpha1
kind: NemoDatastore
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: k8s-nim-operator
  name: nemodatastore-sample
  namespace: nemo
spec:
  secrets:
    datastoreConfigSecret: "nemo-ms-nemo-datastore"
    datastoreInitSecret: "nemo-ms-nemo-datastore-init"
    datastoreInlineConfigSecret: "nemo-ms-nemo-datastore-inline-config"
    giteaAdminSecret: "gitea-admin-credentials"
    lfsJwtSecret: "nemo-ms-nemo-datastore--lfs-jwt" 
  objectStoreConfig:
    credentials:
      user: minioUser
      secretName: nds-minio-existing-secret
      passwordKey: objectStoreSecret
    serveDirect: true
    endpoint: minio.nemo.svc.cluster.local:9000
    bucketName: datastore-dev
    region: object-store-region
    ssl: false
  databaseConfig:
    credentials:
      user: ndsuser
      secretName: nds-pg-existing-secret
      passwordKey: password
    host: nds-pg-postgresql.nemo.svc.cluster.local
    port: 5432
    databaseName: ndsdb
  pvc:
    name: "pvc-shared-data"
    create: true
    storageClass: "local-path"
    volumeAccessMode: ReadWriteOnce
    size: "10Gi"
  expose:
    service:
      port: 3000
      type: ClusterIP
  image:
    repository: "nvcr.io/nvidian/nemo-llm/datastore"
    tag: "25.03-rc11"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
