apiVersion: apps.nvidia.com/v1alpha1
kind: NemoGuardrails
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: k8s-nim-operator
  name: nemoguardrails-sample
  namespace: nemo
spec:
  authSecret: ngc-api-secret
  configStore:
    configMap:
      name: gr-config
  env:
    - name: NIM_ENDPOINT_URL
      value: http://<NIM_SERVICE_ENDPOINT>:<NIM_SERVICE_PORT>/v1
    - name: NIM_ENDPOINT_API_KEY
      value: dummy
  expose:
    service:
      type: ClusterIP
      ports:
        - name: api
          port: 8000
  image:
    repository: nvcr.io/nvidia/nemo-microservices/guardrails
    tag: "25.03"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  metrics:
    serviceMonitor: {}
  replicas: 1
  resources:
    limits:
      cpu: "1"
      ephemeral-storage: 10Gi
