apiVersion: apps.nvidia.com/v1alpha1
kind: NemoEvaluator
metadata:
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: k8s-nim-operator
  name: nemoevaluator-sample
  namespace: nemo
spec:
  image:
    repository: nvcr.io/nvidia/nemo-microservices/evaluator
    tag: "25.02"
    pullPolicy: IfNotPresent
    pullSecrets: []
  expose:
    service:
      port: 7331
  argoWorkflows:
    endpoint: https://argo-workflows-server.nemo.svc.cluster.local:2746
    serviceAccount: argo-workflows-executor
  vectorDB:
    endpoint: http://milvus.nemo.svc.cluster.local:19530
  datastore:
    endpoint: http://datastore-sample.nemo.svc.cluster.local:3000/v1/hf
  databaseConfig:
    host: evaluator-pg-postgresql.nemo.svc.cluster.local
    port: 5432
    databaseName: evaldb
    credentials:
      user: evaluser
      secretName: nev-pg-existing-secret
      passwordKey: password
  replicas: 1
