---
{{- if .Values.operator.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-nim-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "k8s-nim-operator.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "k8s-nim-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
---
{{ if and .Values.operator.admissionController.enabled (eq .Values.operator.admissionController.tls.mode "cert-manager") }}
{{ $issuerType := default "selfsigned" .Values.operator.admissionController.tls.certManager.issuerType -}}
{{ $issuerName := .Values.operator.admissionController.tls.certManager.issuerName -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "k8s-nim-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: helm
spec:
  dnsNames:
    - {{ include "k8s-nim-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "k8s-nim-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
    {{- range .Values.operator.admissionController.tls.certManager.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    kind: {{- if eq (lower $issuerType) "clusterissuer" }} ClusterIssuer {{- else }} Issuer {{- end }}
    name: {{- if eq (lower $issuerType) "selfsigned" }} {{ include "k8s-nim-operator.fullname" . }}-selfsigned-issuer {{- else }} {{ required "operator.admissionController.tls.certManager.issuerName is required when issuerType is 'issuer' or 'clusterissuer'" $issuerName }} {{- end }}
  secretName: {{ include "k8s-nim-operator.fullname" . }}-webhook-server-cert
{{- end }}
---
{{ if and .Values.operator.admissionController.enabled (eq .Values.operator.admissionController.tls.mode "cert-manager") (eq (lower (default "selfsigned" .Values.operator.admissionController.tls.certManager.issuerType)) "selfsigned") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "k8s-nim-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: k8s-nim-operator
    app.kubernetes.io/managed-by: helm
spec:
  selfSigned: {}
{{- end}}