{{- if .Values.nfd.nodeFeatureRules.deviceID }}
kind: NodeFeatureRule
apiVersion: nfd.k8s-sigs.io/v1alpha1
metadata:
  name: nfd-pci-device-rule
  labels:
    app.kubernetes.io/managed-by: k8s-nim-operator
spec:
  rules:
    - name: "NVIDIA PCIe Device Label"
      labelsTemplate: |
        {{`{{ range .pci.device }}pci-{{ .vendor }}-{{ .device }}.present=true`}}
        {{`{{ end }}`}}
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
            class: {op: In, value: ["0300", "0302"]}
{{- end }}
