{{- if .Values.operator.upgradeCRD }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nim-operator-upgrade-crd-hook-sa
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nim-operator-upgrade-crd-hook-role
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nim-operator-upgrade-crd-hook-binding
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
subjects:
  - kind: ServiceAccount
    name: nim-operator-upgrade-crd-hook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nim-operator-upgrade-crd-hook-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nim-operator-upgrade-crd
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    {{- include "k8s-nim-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: "nim-operator"
spec:
  template:
    metadata:
      name: nim-operator-upgrade-crd
      labels:
        {{- include "k8s-nim-operator.labels" . | nindent 8 }}
        app.kubernetes.io/component: "nim-operator"
    spec:
      serviceAccountName: nim-operator-upgrade-crd-hook-sa
      {{- if .Values.operator.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.operator.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: upgrade-crd
          image: {{ include "k8s-nim-operator.fullimage" . }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          resources: {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          command: ["crd-apply-tool"]
          args:
            - "--crds-dir=/opt/nim-operator/crds/"
      restartPolicy: OnFailure
{{- end }}
