/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NIMBuildListerExpansion allows custom methods to be added to
// NIMBuildLister.
type NIMBuildListerExpansion interface{}

// NIMBuildNamespaceListerExpansion allows custom methods to be added to
// NIMBuildNamespaceLister.
type NIMBuildNamespaceListerExpansion interface{}

// NIMCacheListerExpansion allows custom methods to be added to
// NIMCacheLister.
type NIMCacheListerExpansion interface{}

// NIMCacheNamespaceListerExpansion allows custom methods to be added to
// NIMCacheNamespaceLister.
type NIMCacheNamespaceListerExpansion interface{}

// NIMPipelineListerExpansion allows custom methods to be added to
// NIMPipelineLister.
type NIMPipelineListerExpansion interface{}

// NIMPipelineNamespaceListerExpansion allows custom methods to be added to
// NIMPipelineNamespaceLister.
type NIMPipelineNamespaceListerExpansion interface{}

// NIMServiceListerExpansion allows custom methods to be added to
// NIMServiceLister.
type NIMServiceListerExpansion interface{}

// NIMServiceNamespaceListerExpansion allows custom methods to be added to
// NIMServiceNamespaceLister.
type NIMServiceNamespaceListerExpansion interface{}

// NemoCustomizerListerExpansion allows custom methods to be added to
// NemoCustomizerLister.
type NemoCustomizerListerExpansion interface{}

// NemoCustomizerNamespaceListerExpansion allows custom methods to be added to
// NemoCustomizerNamespaceLister.
type NemoCustomizerNamespaceListerExpansion interface{}

// NemoDatastoreListerExpansion allows custom methods to be added to
// NemoDatastoreLister.
type NemoDatastoreListerExpansion interface{}

// NemoDatastoreNamespaceListerExpansion allows custom methods to be added to
// NemoDatastoreNamespaceLister.
type NemoDatastoreNamespaceListerExpansion interface{}

// NemoEntitystoreListerExpansion allows custom methods to be added to
// NemoEntitystoreLister.
type NemoEntitystoreListerExpansion interface{}

// NemoEntitystoreNamespaceListerExpansion allows custom methods to be added to
// NemoEntitystoreNamespaceLister.
type NemoEntitystoreNamespaceListerExpansion interface{}

// NemoEvaluatorListerExpansion allows custom methods to be added to
// NemoEvaluatorLister.
type NemoEvaluatorListerExpansion interface{}

// NemoEvaluatorNamespaceListerExpansion allows custom methods to be added to
// NemoEvaluatorNamespaceLister.
type NemoEvaluatorNamespaceListerExpansion interface{}

// NemoGuardrailListerExpansion allows custom methods to be added to
// NemoGuardrailLister.
type NemoGuardrailListerExpansion interface{}

// NemoGuardrailNamespaceListerExpansion allows custom methods to be added to
// NemoGuardrailNamespaceLister.
type NemoGuardrailNamespaceListerExpansion interface{}
