/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NemoGuardrailLister helps list NemoGuardrails.
// All objects returned here must be treated as read-only.
type NemoGuardrailLister interface {
	// List lists all NemoGuardrails in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.NemoGuardrail, err error)
	// NemoGuardrails returns an object that can list and get NemoGuardrails.
	NemoGuardrails(namespace string) NemoGuardrailNamespaceLister
	NemoGuardrailListerExpansion
}

// nemoGuardrailLister implements the NemoGuardrailLister interface.
type nemoGuardrailLister struct {
	listers.ResourceIndexer[*appsv1alpha1.NemoGuardrail]
}

// NewNemoGuardrailLister returns a new NemoGuardrailLister.
func NewNemoGuardrailLister(indexer cache.Indexer) NemoGuardrailLister {
	return &nemoGuardrailLister{listers.New[*appsv1alpha1.NemoGuardrail](indexer, appsv1alpha1.Resource("nemoguardrail"))}
}

// NemoGuardrails returns an object that can list and get NemoGuardrails.
func (s *nemoGuardrailLister) NemoGuardrails(namespace string) NemoGuardrailNamespaceLister {
	return nemoGuardrailNamespaceLister{listers.NewNamespaced[*appsv1alpha1.NemoGuardrail](s.ResourceIndexer, namespace)}
}

// NemoGuardrailNamespaceLister helps list and get NemoGuardrails.
// All objects returned here must be treated as read-only.
type NemoGuardrailNamespaceLister interface {
	// List lists all NemoGuardrails in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.NemoGuardrail, err error)
	// Get retrieves the NemoGuardrail from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1alpha1.NemoGuardrail, error)
	NemoGuardrailNamespaceListerExpansion
}

// nemoGuardrailNamespaceLister implements the NemoGuardrailNamespaceLister
// interface.
type nemoGuardrailNamespaceLister struct {
	listers.ResourceIndexer[*appsv1alpha1.NemoGuardrail]
}
