/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NIMPipelineLister helps list NIMPipelines.
// All objects returned here must be treated as read-only.
type NIMPipelineLister interface {
	// List lists all NIMPipelines in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.NIMPipeline, err error)
	// NIMPipelines returns an object that can list and get NIMPipelines.
	NIMPipelines(namespace string) NIMPipelineNamespaceLister
	NIMPipelineListerExpansion
}

// nIMPipelineLister implements the NIMPipelineLister interface.
type nIMPipelineLister struct {
	listers.ResourceIndexer[*appsv1alpha1.NIMPipeline]
}

// NewNIMPipelineLister returns a new NIMPipelineLister.
func NewNIMPipelineLister(indexer cache.Indexer) NIMPipelineLister {
	return &nIMPipelineLister{listers.New[*appsv1alpha1.NIMPipeline](indexer, appsv1alpha1.Resource("nimpipeline"))}
}

// NIMPipelines returns an object that can list and get NIMPipelines.
func (s *nIMPipelineLister) NIMPipelines(namespace string) NIMPipelineNamespaceLister {
	return nIMPipelineNamespaceLister{listers.NewNamespaced[*appsv1alpha1.NIMPipeline](s.ResourceIndexer, namespace)}
}

// NIMPipelineNamespaceLister helps list and get NIMPipelines.
// All objects returned here must be treated as read-only.
type NIMPipelineNamespaceLister interface {
	// List lists all NIMPipelines in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.NIMPipeline, err error)
	// Get retrieves the NIMPipeline from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1alpha1.NIMPipeline, error)
	NIMPipelineNamespaceListerExpansion
}

// nIMPipelineNamespaceLister implements the NIMPipelineNamespaceLister
// interface.
type nIMPipelineNamespaceLister struct {
	listers.ResourceIndexer[*appsv1alpha1.NIMPipeline]
}
