apiVersion: v1
kind: Service
metadata:
  name: k8s-nim-operator-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: k8s-nim-operator
    app.kubernetes.io/part-of: k8s-nim-operator
    control-plane: controller-manager
  {{- include "k8s-nim-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "k8s-nim-operator.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.metricsService.ports | toYaml | nindent 2 -}}
