apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-nim-operator
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-nim-operator
    app.kubernetes.io/part-of: k8s-nim-operator
  {{- include "k8s-nim-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.annotations | nindent 4 }}
