/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/v1alpha1"
	scheme "github.com/NVIDIA/k8s-nim-operator/api/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NIMCachesGetter has a method to return a NIMCacheInterface.
// A group's client should implement this interface.
type NIMCachesGetter interface {
	NIMCaches(namespace string) NIMCacheInterface
}

// NIMCacheInterface has methods to work with NIMCache resources.
type NIMCacheInterface interface {
	Create(ctx context.Context, nIMCache *v1alpha1.NIMCache, opts v1.CreateOptions) (*v1alpha1.NIMCache, error)
	Update(ctx context.Context, nIMCache *v1alpha1.NIMCache, opts v1.UpdateOptions) (*v1alpha1.NIMCache, error)
	UpdateStatus(ctx context.Context, nIMCache *v1alpha1.NIMCache, opts v1.UpdateOptions) (*v1alpha1.NIMCache, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NIMCache, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NIMCacheList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NIMCache, err error)
	NIMCacheExpansion
}

// nIMCaches implements NIMCacheInterface
type nIMCaches struct {
	client rest.Interface
	ns     string
}

// newNIMCaches returns a NIMCaches
func newNIMCaches(c *V1alpha1Client, namespace string) *nIMCaches {
	return &nIMCaches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nIMCache, and returns the corresponding nIMCache object, and an error if there is any.
func (c *nIMCaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NIMCache, err error) {
	result = &v1alpha1.NIMCache{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nimcaches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NIMCaches that match those selectors.
func (c *nIMCaches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NIMCacheList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NIMCacheList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nimcaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nIMCaches.
func (c *nIMCaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nimcaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nIMCache and creates it.  Returns the server's representation of the nIMCache, and an error, if there is any.
func (c *nIMCaches) Create(ctx context.Context, nIMCache *v1alpha1.NIMCache, opts v1.CreateOptions) (result *v1alpha1.NIMCache, err error) {
	result = &v1alpha1.NIMCache{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nimcaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nIMCache).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nIMCache and updates it. Returns the server's representation of the nIMCache, and an error, if there is any.
func (c *nIMCaches) Update(ctx context.Context, nIMCache *v1alpha1.NIMCache, opts v1.UpdateOptions) (result *v1alpha1.NIMCache, err error) {
	result = &v1alpha1.NIMCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nimcaches").
		Name(nIMCache.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nIMCache).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nIMCaches) UpdateStatus(ctx context.Context, nIMCache *v1alpha1.NIMCache, opts v1.UpdateOptions) (result *v1alpha1.NIMCache, err error) {
	result = &v1alpha1.NIMCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nimcaches").
		Name(nIMCache.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nIMCache).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nIMCache and deletes it. Returns an error if one occurs.
func (c *nIMCaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nimcaches").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nIMCaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nimcaches").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nIMCache.
func (c *nIMCaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NIMCache, err error) {
	result = &v1alpha1.NIMCache{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nimcaches").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
