/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNemoDatastoreV2s implements NemoDatastoreV2Interface
type FakeNemoDatastoreV2s struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var nemodatastorev2sResource = v1alpha1.SchemeGroupVersion.WithResource("nemodatastorev2s")

var nemodatastorev2sKind = v1alpha1.SchemeGroupVersion.WithKind("NemoDatastoreV2")

// Get takes name of the nemoDatastoreV2, and returns the corresponding nemoDatastoreV2 object, and an error if there is any.
func (c *FakeNemoDatastoreV2s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NemoDatastoreV2, err error) {
	emptyResult := &v1alpha1.NemoDatastoreV2{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(nemodatastorev2sResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoDatastoreV2), err
}

// List takes label and field selectors, and returns the list of NemoDatastoreV2s that match those selectors.
func (c *FakeNemoDatastoreV2s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NemoDatastoreV2List, err error) {
	emptyResult := &v1alpha1.NemoDatastoreV2List{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(nemodatastorev2sResource, nemodatastorev2sKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NemoDatastoreV2List{ListMeta: obj.(*v1alpha1.NemoDatastoreV2List).ListMeta}
	for _, item := range obj.(*v1alpha1.NemoDatastoreV2List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nemoDatastoreV2s.
func (c *FakeNemoDatastoreV2s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(nemodatastorev2sResource, c.ns, opts))

}

// Create takes the representation of a nemoDatastoreV2 and creates it.  Returns the server's representation of the nemoDatastoreV2, and an error, if there is any.
func (c *FakeNemoDatastoreV2s) Create(ctx context.Context, nemoDatastoreV2 *v1alpha1.NemoDatastoreV2, opts v1.CreateOptions) (result *v1alpha1.NemoDatastoreV2, err error) {
	emptyResult := &v1alpha1.NemoDatastoreV2{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(nemodatastorev2sResource, c.ns, nemoDatastoreV2, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoDatastoreV2), err
}

// Update takes the representation of a nemoDatastoreV2 and updates it. Returns the server's representation of the nemoDatastoreV2, and an error, if there is any.
func (c *FakeNemoDatastoreV2s) Update(ctx context.Context, nemoDatastoreV2 *v1alpha1.NemoDatastoreV2, opts v1.UpdateOptions) (result *v1alpha1.NemoDatastoreV2, err error) {
	emptyResult := &v1alpha1.NemoDatastoreV2{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(nemodatastorev2sResource, c.ns, nemoDatastoreV2, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoDatastoreV2), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNemoDatastoreV2s) UpdateStatus(ctx context.Context, nemoDatastoreV2 *v1alpha1.NemoDatastoreV2, opts v1.UpdateOptions) (result *v1alpha1.NemoDatastoreV2, err error) {
	emptyResult := &v1alpha1.NemoDatastoreV2{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(nemodatastorev2sResource, "status", c.ns, nemoDatastoreV2, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoDatastoreV2), err
}

// Delete takes name of the nemoDatastoreV2 and deletes it. Returns an error if one occurs.
func (c *FakeNemoDatastoreV2s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nemodatastorev2sResource, c.ns, name, opts), &v1alpha1.NemoDatastoreV2{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNemoDatastoreV2s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(nemodatastorev2sResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NemoDatastoreV2List{})
	return err
}

// Patch applies the patch and returns the patched nemoDatastoreV2.
func (c *FakeNemoDatastoreV2s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NemoDatastoreV2, err error) {
	emptyResult := &v1alpha1.NemoDatastoreV2{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(nemodatastorev2sResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoDatastoreV2), err
}
