/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNemoEvaluators implements NemoEvaluatorInterface
type FakeNemoEvaluators struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var nemoevaluatorsResource = v1alpha1.SchemeGroupVersion.WithResource("nemoevaluators")

var nemoevaluatorsKind = v1alpha1.SchemeGroupVersion.WithKind("NemoEvaluator")

// Get takes name of the nemoEvaluator, and returns the corresponding nemoEvaluator object, and an error if there is any.
func (c *FakeNemoEvaluators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NemoEvaluator, err error) {
	emptyResult := &v1alpha1.NemoEvaluator{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(nemoevaluatorsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEvaluator), err
}

// List takes label and field selectors, and returns the list of NemoEvaluators that match those selectors.
func (c *FakeNemoEvaluators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NemoEvaluatorList, err error) {
	emptyResult := &v1alpha1.NemoEvaluatorList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(nemoevaluatorsResource, nemoevaluatorsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NemoEvaluatorList{ListMeta: obj.(*v1alpha1.NemoEvaluatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.NemoEvaluatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nemoEvaluators.
func (c *FakeNemoEvaluators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(nemoevaluatorsResource, c.ns, opts))

}

// Create takes the representation of a nemoEvaluator and creates it.  Returns the server's representation of the nemoEvaluator, and an error, if there is any.
func (c *FakeNemoEvaluators) Create(ctx context.Context, nemoEvaluator *v1alpha1.NemoEvaluator, opts v1.CreateOptions) (result *v1alpha1.NemoEvaluator, err error) {
	emptyResult := &v1alpha1.NemoEvaluator{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(nemoevaluatorsResource, c.ns, nemoEvaluator, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEvaluator), err
}

// Update takes the representation of a nemoEvaluator and updates it. Returns the server's representation of the nemoEvaluator, and an error, if there is any.
func (c *FakeNemoEvaluators) Update(ctx context.Context, nemoEvaluator *v1alpha1.NemoEvaluator, opts v1.UpdateOptions) (result *v1alpha1.NemoEvaluator, err error) {
	emptyResult := &v1alpha1.NemoEvaluator{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(nemoevaluatorsResource, c.ns, nemoEvaluator, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEvaluator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNemoEvaluators) UpdateStatus(ctx context.Context, nemoEvaluator *v1alpha1.NemoEvaluator, opts v1.UpdateOptions) (result *v1alpha1.NemoEvaluator, err error) {
	emptyResult := &v1alpha1.NemoEvaluator{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(nemoevaluatorsResource, "status", c.ns, nemoEvaluator, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEvaluator), err
}

// Delete takes name of the nemoEvaluator and deletes it. Returns an error if one occurs.
func (c *FakeNemoEvaluators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nemoevaluatorsResource, c.ns, name, opts), &v1alpha1.NemoEvaluator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNemoEvaluators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(nemoevaluatorsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NemoEvaluatorList{})
	return err
}

// Patch applies the patch and returns the patched nemoEvaluator.
func (c *FakeNemoEvaluators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NemoEvaluator, err error) {
	emptyResult := &v1alpha1.NemoEvaluator{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(nemoevaluatorsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEvaluator), err
}
