/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNemoEntitystores implements NemoEntitystoreInterface
type FakeNemoEntitystores struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var nemoentitystoresResource = v1alpha1.SchemeGroupVersion.WithResource("nemoentitystores")

var nemoentitystoresKind = v1alpha1.SchemeGroupVersion.WithKind("NemoEntitystore")

// Get takes name of the nemoEntitystore, and returns the corresponding nemoEntitystore object, and an error if there is any.
func (c *FakeNemoEntitystores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NemoEntitystore, err error) {
	emptyResult := &v1alpha1.NemoEntitystore{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(nemoentitystoresResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEntitystore), err
}

// List takes label and field selectors, and returns the list of NemoEntitystores that match those selectors.
func (c *FakeNemoEntitystores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NemoEntitystoreList, err error) {
	emptyResult := &v1alpha1.NemoEntitystoreList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(nemoentitystoresResource, nemoentitystoresKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NemoEntitystoreList{ListMeta: obj.(*v1alpha1.NemoEntitystoreList).ListMeta}
	for _, item := range obj.(*v1alpha1.NemoEntitystoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nemoEntitystores.
func (c *FakeNemoEntitystores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(nemoentitystoresResource, c.ns, opts))

}

// Create takes the representation of a nemoEntitystore and creates it.  Returns the server's representation of the nemoEntitystore, and an error, if there is any.
func (c *FakeNemoEntitystores) Create(ctx context.Context, nemoEntitystore *v1alpha1.NemoEntitystore, opts v1.CreateOptions) (result *v1alpha1.NemoEntitystore, err error) {
	emptyResult := &v1alpha1.NemoEntitystore{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(nemoentitystoresResource, c.ns, nemoEntitystore, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEntitystore), err
}

// Update takes the representation of a nemoEntitystore and updates it. Returns the server's representation of the nemoEntitystore, and an error, if there is any.
func (c *FakeNemoEntitystores) Update(ctx context.Context, nemoEntitystore *v1alpha1.NemoEntitystore, opts v1.UpdateOptions) (result *v1alpha1.NemoEntitystore, err error) {
	emptyResult := &v1alpha1.NemoEntitystore{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(nemoentitystoresResource, c.ns, nemoEntitystore, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEntitystore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNemoEntitystores) UpdateStatus(ctx context.Context, nemoEntitystore *v1alpha1.NemoEntitystore, opts v1.UpdateOptions) (result *v1alpha1.NemoEntitystore, err error) {
	emptyResult := &v1alpha1.NemoEntitystore{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(nemoentitystoresResource, "status", c.ns, nemoEntitystore, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEntitystore), err
}

// Delete takes name of the nemoEntitystore and deletes it. Returns an error if one occurs.
func (c *FakeNemoEntitystores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nemoentitystoresResource, c.ns, name, opts), &v1alpha1.NemoEntitystore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNemoEntitystores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(nemoentitystoresResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NemoEntitystoreList{})
	return err
}

// Patch applies the patch and returns the patched nemoEntitystore.
func (c *FakeNemoEntitystores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NemoEntitystore, err error) {
	emptyResult := &v1alpha1.NemoEntitystore{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(nemoentitystoresResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoEntitystore), err
}
