/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	scheme "github.com/NVIDIA/k8s-nim-operator/api/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NemoEntitystoresGetter has a method to return a NemoEntitystoreInterface.
// A group's client should implement this interface.
type NemoEntitystoresGetter interface {
	NemoEntitystores(namespace string) NemoEntitystoreInterface
}

// NemoEntitystoreInterface has methods to work with NemoEntitystore resources.
type NemoEntitystoreInterface interface {
	Create(ctx context.Context, nemoEntitystore *v1alpha1.NemoEntitystore, opts v1.CreateOptions) (*v1alpha1.NemoEntitystore, error)
	Update(ctx context.Context, nemoEntitystore *v1alpha1.NemoEntitystore, opts v1.UpdateOptions) (*v1alpha1.NemoEntitystore, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nemoEntitystore *v1alpha1.NemoEntitystore, opts v1.UpdateOptions) (*v1alpha1.NemoEntitystore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NemoEntitystore, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NemoEntitystoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NemoEntitystore, err error)
	NemoEntitystoreExpansion
}

// nemoEntitystores implements NemoEntitystoreInterface
type nemoEntitystores struct {
	*gentype.ClientWithList[*v1alpha1.NemoEntitystore, *v1alpha1.NemoEntitystoreList]
}

// newNemoEntitystores returns a NemoEntitystores
func newNemoEntitystores(c *AppsV1alpha1Client, namespace string) *nemoEntitystores {
	return &nemoEntitystores{
		gentype.NewClientWithList[*v1alpha1.NemoEntitystore, *v1alpha1.NemoEntitystoreList](
			"nemoentitystores",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.NemoEntitystore { return &v1alpha1.NemoEntitystore{} },
			func() *v1alpha1.NemoEntitystoreList { return &v1alpha1.NemoEntitystoreList{} }),
	}
}
