/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	scheme "github.com/NVIDIA/k8s-nim-operator/api/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NemoDatastoresGetter has a method to return a NemoDatastoreInterface.
// A group's client should implement this interface.
type NemoDatastoresGetter interface {
	NemoDatastores(namespace string) NemoDatastoreInterface
}

// NemoDatastoreInterface has methods to work with NemoDatastore resources.
type NemoDatastoreInterface interface {
	Create(ctx context.Context, nemoDatastore *v1alpha1.NemoDatastore, opts v1.CreateOptions) (*v1alpha1.NemoDatastore, error)
	Update(ctx context.Context, nemoDatastore *v1alpha1.NemoDatastore, opts v1.UpdateOptions) (*v1alpha1.NemoDatastore, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nemoDatastore *v1alpha1.NemoDatastore, opts v1.UpdateOptions) (*v1alpha1.NemoDatastore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NemoDatastore, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NemoDatastoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NemoDatastore, err error)
	NemoDatastoreExpansion
}

// nemoDatastores implements NemoDatastoreInterface
type nemoDatastores struct {
	*gentype.ClientWithList[*v1alpha1.NemoDatastore, *v1alpha1.NemoDatastoreList]
}

// newNemoDatastores returns a NemoDatastores
func newNemoDatastores(c *AppsV1alpha1Client, namespace string) *nemoDatastores {
	return &nemoDatastores{
		gentype.NewClientWithList[*v1alpha1.NemoDatastore, *v1alpha1.NemoDatastoreList](
			"nemodatastores",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.NemoDatastore { return &v1alpha1.NemoDatastore{} },
			func() *v1alpha1.NemoDatastoreList { return &v1alpha1.NemoDatastoreList{} }),
	}
}
